import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Responsive Navbar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
      <div style={{ 
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100vh', // Set the height of the parent element to 100% of the viewport height
      width: '100vw', // Set the width of the parent element to 100% of the viewport width
      color: '#03A062',
    }}>
      <div>Home</div>
    </div>
      </body>
    </>
  )
}
